name: 'SQS'
description: 'Send message via AWS SQS'
branding:
  icon: 'send'
  color: 'blue'
inputs:
  accessKeyId:
    description: 'Access Key Id'
    required: true
  secretAccessKey:
    description: 'Secret Access Key'
    required: true 
  region:
    description: 'Region'
    required: true
  url:
    description: 'AWS SQS url'
    required: true
  message:
    description: 'the message that you want to send'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'